[package]
name = "aws-nitro-enclaves-cose"
version = "0.6.0"
authors = ["Petre Eftime <epetre@amazon.com>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["COSE"]
categories = ["cryptography"]
repository = "https://github.com/awslabs/aws-nitro-enclaves-cose"
description = "This library aims to provide a safe Rust implementation of COSE, with COSE Sign1 currently implemented."
rust-version = "1.71"

[dependencies]
serde_cbor = { version="0.11", features = ["tags"] }
serde_repr = "0.1"
serde_bytes = { version = "0.11", features = ["std"] }
serde_with = { version = "3.3" }
openssl = { version = "0.10", optional = true }
ring = { version = "0.17", optional = true }
aws-lc-rs = { version = "1", optional = true }
der = { version = "0.7", default-features = false, features = ["alloc", "std"], optional = true }
pkcs8 = { version = "0.10", default-features = false, features = ["alloc"], optional = true }
spki = { version = "0.7", default-features = false, features = ["alloc"], optional = true }
tss-esapi = { version = "7.5.1", optional = true }
aws-sdk-kms = { version = "1", optional = true }
tokio = { version = "1.20", features = ["rt", "macros"], optional = true }

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies]
hex = "0.4"
sec1 = { version = "0.7", features = ["alloc", "pkcs8"] }
der = { version = "0.7", default-features = false, features = ["alloc", "std"] }
pkcs8 = { version = "0.10", default-features = false, features = ["alloc"] }
spki = { version = "0.7", default-features = false, features = ["alloc"] }
aws-config = { version = "1" }
aws-sdk-sso = { version = "1" }
aws-sdk-ssooidc = { version = "1" }
aws-sdk-sts = { version = "1" }

[features]
default = ["openssl"]
openssl = ["dep:openssl"]
ring = ["dep:ring", "dep:der", "dep:pkcs8", "dep:spki"]
aws-lc-rs = ["dep:aws-lc-rs", "dep:der", "dep:pkcs8", "dep:spki"]
pem = ["pkcs8?/pem", "spki?/pem"]
key_tpm = ["tss-esapi"]
key_kms = ["aws-sdk-kms", "tokio", "dep:der"]
